apiVersion: apps/v1
kind: Deployment
metadata:
  name: yhrhst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yhrhst
  template:
    metadata:
      labels:
        app: yhrhst
    spec:
      containers:
      - image: okteto.dev/yhrhst:latest
        name: yhrhst
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "31ab42d7-f784-4e69-b957-cdce36e91008"
        - name: Vless_Path
          value: "/56uhryh4wge"
        - name: Vmess_UUID
          value: "31ab42d7-f784-4e69-b957-cdce36e91008"
        - name: Vmess_Path
          value: "/tyjrhestg3trg"
        - name: Share_Path
          value: "/v2link"
